version: "3"
services:
  redis:
   image: redis
   deploy:
    replicas: 1
    resources:
     limit:
      - cpus: 0.01
      - memory: 500m
   networks:
    - back-end
  db:
   image: postgres:9.4
   networks:
    - back-end
   environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
   deploy:
    replicas: 3
    placement:
     constraints:
      - node.role == manager
  app1:
   image: myapp1
   networks:
    - back-end
    - front-end
   ports:
    - 5000:80
   depends_on:
    - db
  app2:
   image: myapp2
   networks:
    - back-end
    - front-end
   ports:
    - 5001:80
   depends_on:
    - redis
  netapp:
   image: netapp
   networks:
    - back-end
   depends_on:
    - redis
    - db

networks:
 back-end:
 front-end:
